import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Footer, Topbar } from "@/components/shared";
import { Quicksand } from "next/font/google";

const quicksand = Quicksand({
  subsets: ['latin'],
  variable: '--font-quicksand'
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${quicksand.variable} bg-primary text-gray-50 font-sans antialiased`}
      >
        <Topbar />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
